[package]
name = "ni"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
reqwest = { version = "0.12.24", features = ["blocking"] }

[dev-dependencies]
assert_cmd = "2.0.17"
assert_fs = "1.1.3"
